### ISSUE TITLE
Problem with fetching tasks

### ISSUE THREAD

**Issue by kirrg001** [Teamwork/vscode-projects#10]
Hi there!

Thanks for adding this plugin to vs code.

I am having trouble using it though. 

The task list is not loading. I have no errors in my vs code developer console.
It just shows "Loading tasks...."

It once showed the tasks in the beginning, but then I wasn't able to open the details of a task. I've restarted VS Code (a couple of times already), but since then, it just shows "Loading tasks...."

I've also tried to reinstall extension, without any luck.

Let me know if I can help. Let me know if you need more details. I am not sure how to debug.

Cheers,
Kate

System: Mac

**Comment by kirrg001** [comment]
Any idea?

**Comment by DeeJayTC** [comment]
Hey, sorry this got lost. 
I will have a look. The extension was not changed in some time my guess is some API was changed. 

Will keep you in the loop.

**Comment by DeeJayTC** [comment]
There was an issue with caching in VSCode 1.45.1 , we temporarily disabled caching in the extension, can you please check if that sorted this for you? @kirrg001 @cube-dan

**Comment by kirrg001** [comment]
Thanks. Works now :)

**Comment by cube-dan** [comment]
Working great now. Thanks Tim!
