### ISSUE TITLE
"Please wait for Project data to be loaded" won’t go away

### ISSUE THREAD

**Issue by cube-dan** [Teamwork/vscode-projects#12]
Tim, 

after clicking the "Create Task" menu item, this:
![image](https://user-images.githubusercontent.com/8559668/80628225-e20a0b00-8a05-11ea-917e-306f1b6cad92.png)

I get an alert message that says "Please wait for Project data to be loaded", this: 
![image](https://user-images.githubusercontent.com/8559668/80628350-1251a980-8a06-11ea-897a-393cd88d4846.png)

All of my tasks seem to be loaded in the sidebar. For example this item, the last in the list, has the tasks I've added, as do all of the other task lists in this screenshot:
![image](https://user-images.githubusercontent.com/8559668/80628578-6197da00-8a06-11ea-84cd-1606624e883b.png)

This may be related to issue #10 

Thus far I've removed and reinstalled the vscode-projects extension and reauthenticated with the twp site. 

Please let me know if you need any more info or would like me to try something specific on my end to debug.

**Comment by DeeJayTC** [comment]
This was actually fixed in the last update

**Comment by cube-dan** [comment]
Thanks Tim. It's working again ... thanks for your hard work!
