### ISSUE TITLE
Interested in contributions?

### ISSUE THREAD

**Issue by andrewconnell** [Teamwork/vscode-projects#13]
Love Teamwork!

Would like to submit a few changes to the extension, including:

- add task ID to the Adaptive Card display
- add action to Adaptive Card to mark a task as complete / update progress
- add action to reference in a comment on a task a link to the commit associated with the comment
- fix date display in the **due date** fact set to match date format elsewhere in the project
- change date display to be more universal... not DD-MM-YYYY or MM-DD-YYYY but > MMM DD, YYYY

Interested in contributions?

**Comment by DeeJayTC** [comment]
Hey @andrewconnell more than happy yea. 

If you would just create a pull request with your changes im more than happy to look at and merge it!

**Comment by andrewconnell** [comment]
On it... 

![](https://media.giphy.com/media/GCvktC0KFy9l6/giphy.gif)

Prefer if I open issues stating the issue, proposed resolution/fix/implementation & then PR that closes the issue, all as separate PR's, or just one big PR to this issue?

**Comment by DeeJayTC** [comment]
Think i prefer issue + proposed fix, easier to go through but at the end, you're working on it...so whatever works good for you will work for me :)

**Comment by andrewconnell** [comment]
@DeeJayTC said:
> Think i prefer issue + proposed fix

That's my preference as well... I'll submit a few proposals and you can approve

**Comment by andrewconnell** [comment]
Closing this issue as recreated individual issues for items mentioned in OP, based on this thread.
