### ISSUE TITLE
Extension's settings file should be in .vscode folder, not root

### ISSUE THREAD

**Issue by andrewconnell** [Teamwork/vscode-projects#14]
The extension's configuration file is saved in the root of the repo.

Shouldn't it be in the **.vscode** folder in the project, considering it's only applicable in VSCode?

**Comment by DeeJayTC** [comment]
Hey @andrewconnell ,
this was made to make the settings shareable. 

The settings assign a project to a repository, more than likely everyone working on the repository is using the same project. 
Thats why we thought this setting should be part of the repo.

**Comment by andrewconnell** [comment]
Right... it still is when it's saved in the **.vscode** folder. The idea of that folder is to hold settings specific to VSCode... and since this file contains settings for a VSCode extension that wouldn't be used outside of VSCode. This is the same concept with configurations, settings & workflows files saved to the **.github** folder for repos saved to GH.

Seemed like putting it in the root dirty-ed up the project files.
