### ISSUE TITLE
App Not Found Error

### ISSUE THREAD

**Issue by allordacia** [Teamwork/vscode-projects#29]
**This is a Teamwork passion project and not officially supported by the team**

The creators and maintainers of this project are doing it with enthusiasm and happiness, in odd moments between other projects and possibly even in their spare time. Please be kind to them, and understand that although they hope to get the time & energy to fix your bug :crossed_fingers:, this is not an officially supported product or service, and therefore doing so is not a part of their day jobs.

**Describe the bug**
When trying to login through VSCode, I get an error upon logging into my account saying that the "App Not Found"

**To Reproduce**
1. Go to the extension in VSCode
2. Click on Login or the Profile Icon
3. Browser launches to login to Teamwork account

**Expected behavior**
Should be able to login to teamwork through the browser to authorize access to the extension

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome and firefox

**Additional context**

**Comment by Flexicon** [comment]
Hi @allordacia , thanks for bringing this to our attention.

Our authentication scheme made it a requirement to use developer portal app credentials late last year for any OAuth apps. 
We'll need to add them in and update the plugin.
