### ISSUE TITLE
Date displayed in Teamwork panel for task or comment isn't same as the actual task or comment

### ISSUE THREAD

**Issue by Cenay** [Teamwork/vscode-projects#7]
When viewing a task in Teamwork Project panel inside VSCode, the dates and times on a task or comment are months different from the actual task/comment date and time. 

Recorded a video of the issue here:
https://www.screencast.com/t/xRSdLWCrx

I will leave this video online for 3 months.

**Comment by DeeJayTC** [comment]
Hey Cenay, thats a bug indeed.
Should be fixed in the next days. 

Thanks a lot for taking the time to report it!

**Comment by DeeJayTC** [comment]
Hey Cenay,
I actually fixed this just now, you should see a new version ready to install within the next few minutes. 

Please let me know if that solved the issue for you.

**Comment by Cenay** [comment]
@DeeJayTC -- Sorry for delay, it did resolve the issue, thanks for the prompt attention.
