### ISSUE TITLE
Several issues with extension (Task details fail, no tracking time, ...)

### ISSUE THREAD

**Issue by Tazaf** [Teamwork/vscode-projects#9]
Hi 👋 

We've just started using Teamwork in my company, and I was thrilled to see that there is an extension for VS Code.

So I tried it to see what was available through it and, as the title mentions, I've got several issues with it.

A little bit of context first : I'm using WSL1 on a Windows 10, and I'm working on VS Code through WSL.

As [the documentation says](https://github.com/Teamwork/vscode-projects#linux-users), I used  the APIKey to connect to Teamwork, which I fetched from my profile on TW.

Here's my issues:
* I can't get the details of a task. Each time I try it, the task window shows `undefined`...
  ![image](https://user-images.githubusercontent.com/7702322/73451592-3bf82780-4368-11ea-8663-900f660d3cfc.png)
  ... and the VS Code's notification center shows a notification.
  ![image](https://user-images.githubusercontent.com/7702322/73451575-30a4fc00-4368-11ea-8978-33e6028f5b5c.png)
* I've got an issue similar to the one described in #8 
  ![image](https://user-images.githubusercontent.com/7702322/73451663-6d70f300-4368-11ea-96df-847248e9aade.png)
  I can't open the "Installation du serveur de prod" task. When clicking on it, the extension behaves exactly as the previous bullet point.
* I can't seem to see anywhere on the UI or the VS Code commands how to use the time tracking capabilities described in the documentation.

Thank you for your help !

**Comment by DeeJayTC** [comment]
Hey @Tazaf ,
can you try if you have the same issues when running VS Code on your Windows itself?

We tried to reproduce the issues here and do not seem to be able to reproduce any of that. Might be related to WSL itself.

**Comment by DeeJayTC** [comment]
Hey @Tazaf ,
additionally, can you check if you see any error in the developer console?

When you have VS Code open you can 
go to commands -> open developer tools
and commands - > open webview developer tools. 

You should be able to see errors there. Can you send them to us if you have any?

Also the Output view (when set to extensions on the right side) could potentially have errors that would help us find out whats going wrong for you.

**Comment by DeeJayTC** [comment]
Closing for no response. Please reopen and update issue with answers if you want to.

**Comment by Tazaf** [comment]
Yeah, sorry, I've been absolutely busy and didn't have any time to try and test what you've asked me 🙏 

I'll reopen the issue as soon as I have something to report back to you.

Sorry, again !

**Comment by Tazaf** [comment]
Hi @DeeJayTC 

I tried reinstalling the VS Code extension to see if I could reproduce my problems and give you more information about them.

Turns out that I couldn't reproduce! Everything seems to be working as expected (at least, I don't have any error messages).

Thanks for your time.
